"""use review model instead of association table

Revision ID: 0bc353d23b88
Revises: af6e4a1d9c3f
Create Date: 2024-07-10 11:17:42.866723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc353d23b88'
down_revision = 'af6e4a1d9c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('shoe_id', sa.INTEGER(), nullable=False),
    sa.Column('purchase_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['shoe_id'], ['shoes.id'], name='fk_review_shoe_id_shoes'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_review_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'shoe_id')
    )
    # ### end Alembic commands ###
