"""remove username from Review model

Revision ID: 298f4d885642
Revises: deaafc6b1e32
Create Date: 2024-06-26 16:01:26.519336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298f4d885642'
down_revision = 'deaafc6b1e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_reviews')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_username_users'), 'users', ['username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_username_users'), type_='foreignkey')
        batch_op.drop_column('username')

    op.create_table('_alembic_tmp_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=200), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('shoe_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['shoe_id'], ['shoes.id'], name='fk_reviews_shoe_id_shoes'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_reviews_user_id_users'),
    sa.ForeignKeyConstraint(['username'], ['users.username'], name='fk_reviews_username_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
