"""remove username from Review model

Revision ID: 378a248ac6c8
Revises: 298f4d885642
Create Date: 2024-06-26 16:01:44.148144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378a248ac6c8'
down_revision = '298f4d885642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_username_users', type_='foreignkey')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_reviews_username_users', 'users', ['username'], ['username'])

    # ### end Alembic commands ###
