"""add image_url to shoe

Revision ID: deaafc6b1e32
Revises: 99c980ef5826
Create Date: 2024-06-26 09:52:50.225600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deaafc6b1e32'
down_revision = '99c980ef5826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
